---
- include_tasks: preflight.yml
  tags:
    - blackbox_exporter_install
    - blackbox_exporter_configure
    - blackbox_exporter_run

- include_tasks:
    file: install.yml
    apply:
      become: true
  tags:
    - blackbox_exporter_install

- include_tasks:
    file: configure.yml
    apply:
      become: true
  tags:
    - blackbox_exporter_configure

- name: ensure blackbox_exporter service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: started
    enabled: true
  tags:
    - blackbox_exporter_run
